services:
  - type: web
    name: personalportfolio-hbc7
    runtime: static
    rootDir: justus-portfolio
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
